set_property PACKAGE_PIN N11 [get_ports CLK_12M]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_12M]
set_property PACKAGE_PIN T2 [get_ports RST_BTN_N]
set_property IOSTANDARD LVCMOS33 [get_ports RST_BTN_N]
set_property PACKAGE_PIN M12 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]
set_property PACKAGE_PIN N6 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
