set_property PACKAGE_PIN R13 [get_ports {eth_txd_o[1]}]
set_property PACKAGE_PIN T12 [get_ports {eth_txd_o[0]}]
set_property PACKAGE_PIN N11 [get_ports clk_i]
set_property PACKAGE_PIN T2 [get_ports rst_i]
set_property PACKAGE_PIN N16 [get_ports eth_mdc_o]
set_property PACKAGE_PIN P15 [get_ports eth_mdio_io]
set_property PACKAGE_PIN P16 [get_ports eth_refclk_o]
set_property PACKAGE_PIN R15 [get_ports eth_rstn_o]
set_property PACKAGE_PIN L14 [get_ports eth_txen_o]

set_property PACKAGE_PIN N4 [get_ports tx_empty_i]
set_property PACKAGE_PIN R2 [get_ports tx_eof_i]
set_property PACKAGE_PIN L5 [get_ports tx_rden_o]

set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rstn_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_eof_i]
set_property IOSTANDARD LVCMOS33 [get_ports eth_refclk_o]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdc_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_empty_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txen_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_rden_o]
